//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fieldtool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MRUFile1 {
            get {
                return ((string)(this["MRUFile1"]));
            }
            set {
                this["MRUFile1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MRUFile2 {
            get {
                return ((string)(this["MRUFile2"]));
            }
            set {
                this["MRUFile2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MRUFile3 {
            get {
                return ((string)(this["MRUFile3"]));
            }
            set {
                this["MRUFile3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plum")]
        public global::System.Drawing.Color AccPlotNoDataColor {
            get {
                return ((global::System.Drawing.Color)(this["AccPlotNoDataColor"]));
            }
            set {
                this["AccPlotNoDataColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MapScalebarActive {
            get {
                return ((bool)(this["MapScalebarActive"]));
            }
            set {
                this["MapScalebarActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RightTop")]
        public global::SharpMap.Rendering.Decoration.MapDecorationAnchor MapLegendAnchor {
            get {
                return ((global::SharpMap.Rendering.Decoration.MapDecorationAnchor)(this["MapLegendAnchor"]));
            }
            set {
                this["MapLegendAnchor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 8.25pt")]
        public global::System.Drawing.Font MapLegendFont {
            get {
                return ((global::System.Drawing.Font)(this["MapLegendFont"]));
            }
            set {
                this["MapLegendFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MapLegendTextColor {
            get {
                return ((global::System.Drawing.Color)(this["MapLegendTextColor"]));
            }
            set {
                this["MapLegendTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MapLegendBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["MapLegendBackgroundColor"]));
            }
            set {
                this["MapLegendBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MapLegendBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["MapLegendBorderColor"]));
            }
            set {
                this["MapLegendBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MapLegendActive {
            get {
                return ((bool)(this["MapLegendActive"]));
            }
            set {
                this["MapLegendActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MapLegendBorderRoundEdges {
            get {
                return ((bool)(this["MapLegendBorderRoundEdges"]));
            }
            set {
                this["MapLegendBorderRoundEdges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float MapLegendBackgroundAlpha {
            get {
                return ((float)(this["MapLegendBackgroundAlpha"]));
            }
            set {
                this["MapLegendBackgroundAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int VisualizerTextsize {
            get {
                return ((int)(this["VisualizerTextsize"]));
            }
            set {
                this["VisualizerTextsize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int VisualizerMarkersize {
            get {
                return ((int)(this["VisualizerMarkersize"]));
            }
            set {
                this["VisualizerMarkersize"] = value;
            }
        }
    }
}
